---
- name: Converge
  hosts: all
  become: yes
  vars:
    pkg_list:
      - name: haveged
      - name: unattended-upgrades
        debconf:
          - question: unattended-upgrades/enable_auto_updates
            vtype: boolean
            value: true
  roles:
    - role: role-pkg
